### ISSUE TITLE
Use default or installed icon theme in file browser

### ISSUE THREAD

**Issue by tmarti2** [bodil/vscode-file-browser#13]
At the moment all files (and dirs) have the same icon, no matter their extensions. It would be nice if your file browser could use icons used by vscode (for example in palette file browser, or tabs) to make search even easier.

Thanks again !

**Comment by bodil** [comment]
Unfortunately, the VSCode QuickPick API doesn't currently allow that. Believe me, I wish it did.

**Comment by fbob** [comment]
No news on this front ?
Very very nice extension by the way: a must have for me !

**Comment by bodil** [comment]
Themable codicons is not something being worked on upstream at all, afaik. You could try submitting a feature request.

**Comment by fbob** [comment]
Thanks for the precision and congrats for your awesome extension.

**Comment by sibbng** [comment]
I have made a custom script that adds icons, here it is: https://gist.github.com/sibbng/57103058c75e7d5dc3f2df84941bc858

Replace VS Code's workbench.html with that.

Windows path: `C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench\workbench.html`

**Note: You have to modify workbench.html after every VS Code update.**

Preview:
![image](https://user-images.githubusercontent.com/19991745/103175110-a7988c80-4878-11eb-9cfb-778d07d513d9.png)
