### ISSUE TITLE
lag under WSL

### ISSUE THREAD

**Issue by basaran** [bodil/vscode-file-browser#14]
Hello, there is certain lag (about 1s) when the plugin is ran under WSL. The lag occurs while traversing the directories and during initial listing.

You can observe the lag in the screen capture. Please notice the title update and the time it takes to display the contents.

![here](https://user-images.githubusercontent.com/30809170/91937336-ab981180-ecbf-11ea-9a59-0300e16c4ce2.gif)

**Comment by bodil** [comment]
Is this WSL1 or 2? I'm using it with WSL2 myself and I'm not seeing anything like this. Windows filesystem operations are notoriously slow but I've not seen it as bad as this before.

**Comment by basaran** [comment]
WSL-2 ubuntu on the latest anything Windows 10. I tried disabling all extensions and just enabling File Browser + WSL and it was still the same lag. This weekend, when I have the time I will run the debugger on it and let you know.

**Comment by bodil** [comment]
The only thing it really could be if it's the extension causing the lag is the `.gitignore` checker, can you try disabling it to see if it gets better? Specifically, set `file-browser.hideIgnoredFiles` to `false` in your settings, that should stop it from walking up the filesystem tree looking for `.gitignore` files. Although this too works on my WSL2 without the lag, so it's a long shot, but it's the only thing I can think of.

**Comment by basaran** [comment]
That was it.

```
"file-browser.hideIgnoredFiles" : false
```

and disabling:

```
"file-browser.hideDotfiles": false,
```

also provided additional boost. Thank you very much.
