### ISSUE TITLE
Feature Request: Open Tree View

### ISSUE THREAD

**Issue by basaran** [bodil/vscode-file-browser#15]
Hello,

Thank you for the plugin. Do you have any plans to include expanding folders in the main view and keeping the state on the next run? This way, we can use it to replace the stock vs code file browser, which is bothersome as it slides itself into the editor area (bothersome when you have two vertical panes).

**Comment by bodil** [comment]
Sorry, this is way out of scope for this extension, not to mention impossible to do given the current state of the QuickPick API.
