### ISSUE TITLE
Show an indication when enumerating folder with lots of files

### ISSUE THREAD

**Issue by rbadapanda** [bodil/vscode-file-browser#20]
Hello,

I have a folder with 12385 files. I have one of these files open. When I try to open the file browser. For a few seconds I don't see anything happening on the screen.

Can you make such that the dialog shows up (with whatever data it has) first. And incrementally update the contents in the dialog ?

to simulate you might use the following to create lot's of files
`for i in $(echo {1..12385}); do touch temp_file_$i; done`

**Comment by stevenguh** [comment]
The indication can probably be done by setting the `busy` property of a `QuickPick`

**Comment by bodil** [comment]
Fixed by #23.
