### ISSUE TITLE
Feature request: ctrl+h for parent dir (like Spacemacs Helm)

### ISSUE THREAD

**Issue by dwadden** [bodil/vscode-file-browser#21]
Thanks for making this! I really missed Helm in VSCode.

Like the title says, I've got an extremely minor feature request. Can you add ctrl+h as an alternative to `../` as a way to  navigate to parent directory to mimic the behavior of Spacemacs? I'm also happy to add this if you can tell me which file to modify.

Thanks,

Dave

**Comment by stevenguh** [comment]
You can do this by adding/merging the following json in your user's `keybindings.json`
```
[
	{
		"key": "ctrl+h",
		"command": "file-browser.stepOut",
		"when": "inFileBrowser"
	},
	{
		"key": "ctrl+l",
		"command": "file-browser.stepIn",
		"when": "inFileBrowser"
	}
]
```

**Comment by dwadden** [comment]
Perfect, much appreciated.
