### ISSUE TITLE
Obviously creating folder

### ISSUE THREAD

**Issue by ivklgn** [bodil/vscode-file-browser#33]
Now, if i type some name of file - i see:

<img width="722" alt="Screenshot 2022-07-09 at 00 49 48" src="https://user-images.githubusercontent.com/15219574/178074809-50049d1c-4a54-4042-8ff0-5bca01c6f63b.png">
 
if i want create folder i must know add `/` , and item for folder create activate, but interface make type folder name again

<img width="455" alt="Screenshot 2022-07-09 at 00 50 58" src="https://user-images.githubusercontent.com/15219574/178074935-f9e2e9f5-486a-4d7b-b31d-2ebe3c80cb4c.png">

@bodil what you think about add  "Create folder" item under "Create file" in first screen?

**Comment by goyalyashpal** [comment]
umh, i don't understand what you are saying...

for me, here's the flow:

1. trigger `file browser: open`
2. type `abc`
3. press enter 
4. --> a new buffer named "abc" will open
5. press "ctrl + s" to save 
6. --> the buffer will be saved as a new file `./abc` i.e. at the current location

Or
1. type `/` 
2. --> this makes it take "da" as directory
3. type "fgh"
4. repeat step 3. to 5. above
5. --> the buffer will be saved as a new file `./da/fgh` i.e. under the folder named "da" under current directory

**Comment by goyalyashpal** [comment]
Hey, If the above solves your problem, then i think this issue can be closed :)

**Comment by goyalyashpal** [comment]
> if i want create folder i must know add `/` , and item for folder create activate, but interface make type folder name again

ohkay, i got it.. 

no, you don't have to add the folder name again, you just have to press down to highlight that line saying "Create this folder" and press enter.

that will directly create the folder.

**Comment by goyalyashpal** [comment]
Hey, 
If the above solves your problem or you no longer have this problem, 
then can you close this issue 😇

**Comment by goyalyashpal** [comment]
@kalagin ping

**Comment by ivklgn** [comment]
@goyalyashpal thank u!
