### ISSUE TITLE
Broken in Vscode Version: 1.73.0

### ISSUE THREAD

**Issue by rbadapanda** [bodil/vscode-file-browser#36]
Issue: After launching the file selector, The cursor does no appear in the input box.

**Comment by wxjzeke** [comment]
+1. Same issue. After launching the file browser the cursor is set right in, then take action step-in or step-out , the cursor is lost and can not type in.
![Screen Recording 11-9-2022 at 10 30 AM](https://user-images.githubusercontent.com/8022227/200722909-95bc6cb8-5f72-458f-a73a-3f8212afbb6e.gif)

**Comment by wxjzeke** [comment]
🤔 . Seems the duplicate of https://github.com/bodil/vscode-file-browser/issues/35

**Comment by rbadapanda** [comment]
Noticed that this issue has been fixed in master branch but the extension release has not yet happened. The new version is 0.2.14, fix is in `atariq11700` 's repository.
